#!/usr/bin/env python
from os import listdir
from os.path import isdir, join

#DIR="/Users/monra/Desktop/Z68X-UD3-B3"
#DIR = "/Users/monra/Desktop/MonRanaonda"
DIR="/Users/monra/Desktop/monra-Satellite-C655"

print "Length,Gateways,GatewayRouters,Clients,ClientRouters"

subdirs=[f for f in listdir(DIR)]
subdirs=[f for f in subdirs if f[0] == 'd']
for s in subdirs:
    l = s.split(" ")

    # abre cada arquivo e extrai os dados
    #print "#", s
    with open(join(join(DIR, s), "clientslog.csv")) as f:
        lines = f.readlines()

    tmean = 0
    okcnt = 0
    tcnt = 0
    ecnt = 0

    for li in lines:
        data = li.split(";")
        tcnt = tcnt + 1
        if data[7][0] != 's':
            ecnt = ecnt + 1
        else:
            tmean = tmean + int(data[6])
            okcnt = okcnt + 1
    f.close()

    # abre cada arquivo e extrai os dados
    #print "#", s
    with open(join(join(DIR, s), "gatewayslog.csv")) as f:
        lines = f.readlines()
        
        gw_tmean = 0
        gw_okcnt = 0
        gw_tcnt = 0
        gw_ecnt = 0
        
        for li in lines:
            data = li.split(";")
            gw_tcnt = gw_tcnt + 1
            if data[5][0] != 's':
                gw_ecnt = gw_ecnt + 1
            else:
                gw_tmean = gw_tmean + int(data[4])
                gw_okcnt = gw_okcnt + 1
        f.close()

        with open(join(join(DIR, s), "running-stats.csv")) as f:
            lines = f.readlines()

        cpu_tmean = 0
        cpu_tcnt = 0
        cpu_end = int(lines[-1].split(";")[-2])
                
        for li in lines:
            data = li.split(";")
            cpu_tcnt = cpu_tcnt + 1
            cpu_tmean = cpu_tmean + int(data[-1].split(".")[0])
        f.close()


    print "%s, %s, %s, %s, %s, %d, %d, %d, %d, %d, %d, %d" % (l[5],l[7],l[9],l[11],l[13], tmean/okcnt, ecnt*100/tcnt,gw_tmean/gw_okcnt, gw_ecnt*100/gw_tcnt, tmean/okcnt - gw_tmean/gw_okcnt, cpu_tmean/cpu_tcnt, cpu_end)


