#!/bin/sh

docker network create --ipv6 --subnet=bbbb::/64 routers
docker network create --ipv6 --subnet=cccc::/64 clients
docker network create --ipv6 --subnet=aaaa:1::/64 gateways

sysctl net.ipv6.conf.all.forwarding=0

