#!/bin/sh

sudo ./xiot -d 30 -r 10000 -l 8 -g 2 -G 1 -c 2 -C 1 start
sudo ./xiot -d 30 -r 10000 -l 16 -g 2 -G 1 -c 2 -C 1 start
sudo ./xiot -d 30 -r 10000 -l 32 -g 2 -G 1 -c 2 -C 1 start
sudo ./xiot -d 30 -r 10000 -l 64 -g 2 -G 1 -c 2 -C 1 start

sudo ./xiot -d 30 -r 10000 -l 8 -g 2 -G 2 -c 2 -C 2 start
sudo ./xiot -d 30 -r 10000 -l 16 -g 2 -G 2 -c 2 -C 2 start
sudo ./xiot -d 30 -r 10000 -l 32 -g 2 -G 2 -c 2 -C 2 start
sudo ./xiot -d 30 -r 10000 -l 64 -g 2 -G 2 -c 2 -C 2 start

sudo ./xiot -d 30 -r 10000 -l 8 -g 3 -G 2 -c 3 -C 2 start
sudo ./xiot -d 30 -r 10000 -l 16 -g 3 -G 2 -c 3 -C 2 start
sudo ./xiot -d 30 -r 10000 -l 32 -g 3 -G 2 -c 3 -C 2 start
sudo ./xiot -d 30 -r 10000 -l 64 -g 3 -G 2 -c 3 -C 2 start

sudo ./xiot -d 30 -r 10000 -l 8 -g 3 -G 3 -c 3 -C 3 start
sudo ./xiot -d 30 -r 10000 -l 16 -g 3 -G 3 -c 3 -C 3 start
sudo ./xiot -d 30 -r 10000 -l 32 -g 3 -G 3 -c 3 -C 3 start
sudo ./xiot -d 30 -r 10000 -l 64 -g 3 -G 3 -c 3 -C 3 start

sudo ./xiot -d 30 -r 10000 -l 8 -g 4 -G 3 -c 4 -C 3 start
sudo ./xiot -d 30 -r 10000 -l 16 -g 4 -G 3 -c 4 -C 3 start
sudo ./xiot -d 30 -r 10000 -l 32 -g 4 -G 3 -c 4 -C 3 start
sudo ./xiot -d 30 -r 10000 -l 64 -g 4 -G 3 -c 4 -C 3 start

sudo ./xiot -d 30 -r 10000 -l 8 -g 4 -G 4 -c 4 -C 4 start
sudo ./xiot -d 30 -r 10000 -l 16 -g 4 -G 4 -c 4 -C 4 start
sudo ./xiot -d 30 -r 10000 -l 32 -g 4 -G 4 -c 4 -C 4 start
sudo ./xiot -d 30 -r 10000 -l 64 -g 4 -G 4 -c 4 -C 4 start
