#!/bin/sh

sudo docker run -it --privileged --sysctl net.ipv6.conf.all.disable_ipv6=0 --sysctl net.ipv6.conf.all.forwarding=1 --sysctl net.ipv6.conf.eth0.accept_ra=2 --sysctl net.ipv6.conf.all.proxy_ndp=1 ipv6-base 
