#!/bin/sh

#  -c Clients per Clients Routers
#  -g Gateways per Gateways Routers
#  -m Motes per Gateway
#  -C Client Routers
#  -G Gateway Routers
#  -l Data size (bytes) # Datagram Payload Size
#  -r Requests # Number of requests of each client
#  -t Timeout (s) # Gateway to UDP network. There is no timeout on XIA network
#  -v Data Volume # Folder name
#  -d Delay (s) # Base delay variable for initializations
#  -a Internet Architecture

# Aumentar o número de client routers (C) e de clients por consequência (c) 

sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 1 -G 1 -c 1 -C 1 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 1 -G 1 -c 1 -C 2 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 1 -G 1 -c 1 -C 3 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 1 -G 1 -c 1 -C 4 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 1 -G 1 -c 1 -C 5 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 1 -G 1 -c 1 -C 7 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 1 -G 1 -c 1 -C 8 start

#l      g       G       c       C
#8	1	1	1	1
#8	1	1	1	2
#8	1	1	1	3
#8	1	1	1	4
#8	1	1	1	5
#8	1	1	1	7
#8	1	1	1	8

sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 1 -G 1 -c 2 -C 1 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 1 -G 1 -c 2 -C 2 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 1 -G 1 -c 2 -C 3 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 1 -G 1 -c 2 -C 4 start

#8	1	1	2	1
#8	1	1	2	2
#8	1	1	2	3
#8	1	1	2	4

sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 1 -G 1 -c 3 -C 2 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 1 -G 1 -c 4 -C 1 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 1 -G 1 -c 4 -C 2 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 1 -G 1 -c 5 -C 1 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 1 -G 1 -c 6 -C 1 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 1 -G 1 -c 7 -C 1 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 1 -G 1 -c 8 -C 1 start

#8	1	1	3	2
#8	1	1	4	1
#8	1	1	4	2
#8	1	1	5	1
#8	1	1	7	1
#8	1	1	8	1

# Aumentar o número de gateways (g) e gateway routers (G) incrementando o número de clientes também

sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 2 -G 1 -c 1 -C 1 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 2 -G 1 -c 1 -C 2 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 2 -G 1 -c 1 -C 3 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 2 -G 1 -c 1 -C 4 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 2 -G 1 -c 2 -C 1 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 2 -G 2 -c 2 -C 2 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 3 -G 2 -c 3 -C 2 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 3 -G 3 -c 3 -C 3 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 3 -c 4 -C 3 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 4 -c 4 -C 4 start

#8	2	1	1	1
#8	2	1	1	2
#8	2	1	1	3
#8	2	1	1	4
#8	2	1	2	1
#8	2	2	2	2
#8	3	2	3	2
#8	3	3	3	3
#8	4	3	4	3
#8	4	4	4	4

# Aumentar o número de gateways (g) e gateway routers (G) incrementando o número de clientes e tamanho de pacotes também

sudo ./xiot -a xia -d 30 -r 10000 -l 16 -g 2 -G 1 -c 1 -C 1 start
sudo ./xiot -a xia -d 30 -r 10000 -l 16 -g 2 -G 1 -c 2 -C 1 start
sudo ./xiot -a xia -d 30 -r 10000 -l 16 -g 2 -G 2 -c 2 -C 2 start

#16	2	1	1	1
#16	2	1	2	1
#16	2	2	2	2

sudo ./xiot -a xia -d 30 -r 10000 -l 32 -g 2 -G 1 -c 1 -C 1 start
sudo ./xiot -a xia -d 30 -r 10000 -l 32 -g 2 -G 1 -c 2 -C 1 start
sudo ./xiot -a xia -d 30 -r 10000 -l 32 -g 2 -G 2 -c 2 -C 2 start

#32	2	1	1	1
#32	2	1	2	1
#32	2	2	2	2

sudo ./xiot -a xia -d 30 -r 10000 -l 64 -g 2 -G 1 -c 1 -C 1 start
sudo ./xiot -a xia -d 30 -r 10000 -l 64 -g 2 -G 1 -c 2 -C 1 start
sudo ./xiot -a xia -d 30 -r 10000 -l 64 -g 2 -G 2 -c 2 -C 2 start
sudo ./xiot -a xia -d 30 -r 10000 -l 64 -g 3 -G 2 -c 3 -C 2 start
sudo ./xiot -a xia -d 30 -r 10000 -l 64 -g 3 -G 3 -c 3 -C 3 start
sudo ./xiot -a xia -d 30 -r 10000 -l 64 -g 4 -G 3 -c 4 -C 3 start

#64	2	1	1	1
#64	2	1	2	1
#64	2	2	2	2
#64	3	2	3	2
#64	3	3	3	3
#64	4	3	4	3

