#!/bin/sh

#  -c Clients per Clients Routers
#  -g Gateways per Gateways Routers
#  -m Motes per Gateway
#  -C Client Routers
#  -G Gateway Routers
#  -l Data size (bytes) # Datagram Payload Size
#  -r Requests # Number of requests of each client
#  -t Timeout (s) # Gateway to UDP network. There is no timeout on XIA network
#  -v Data Volume # Folder name
#  -d Delay (s) # Base delay variable for initializations
#  -a Internet Architecture

# Aumentar o número de client routers (C) e de clients por consequência (c) 

sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 2 -c 1 -C 1 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 2 -c 1 -C 2 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 2 -c 1 -C 4 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 2 -c 1 -C 8 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 2 -c 1 -C 16 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 2 -c 2 -C 1 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 2 -c 2 -C 2 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 2 -c 2 -C 4 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 2 -c 2 -C 8 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 2 -c 2 -C 16 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 2 -c 3 -C 1 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 2 -c 3 -C 2 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 2 -c 3 -C 4 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 2 -c 3 -C 8 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 2 -c 3 -C 16 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 2 -c 4 -C 1 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 2 -c 4 -C 2 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 2 -c 4 -C 4 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 2 -c 4 -C 8 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 2 -c 4 -C 16 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 2 -c 5 -C 1 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 2 -c 5 -C 2 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 2 -c 5 -C 4 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 2 -c 5 -C 8 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 2 -c 5 -C 16 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 2 -c 5 -C 16 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 2 -c 6 -C 1 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 2 -c 6 -C 2 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 2 -c 6 -C 4 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 2 -c 6 -C 8 start
sudo ./xiot -a xia -d 30 -r 10000 -l 8 -g 4 -G 2 -c 6 -C 16 start

