#!/bin/bash
#
# Copyright 2017 MonRá
#

XIOTDIR="$(cd "$(dirname "$0")" && pwd)"
NAME=`basename $0`

help()
{
	cat << EOF

Start or stop the XIoT network testing services.

usage: $NAME [-cgCGmdtr] [-c <clients_per_router>] [-g <gateways_per_router>] [-m <motes_per_gateway>]
             [-C <client_routers>] [-G <gateway_routers>] [-r <resquests>]
             [-t <timeout>] [-d <data_size>]  [start|stop|kill|prune|single|build|print|manual]
where:
  -c Clients per Clients Routers
  -g Gateways per Gateways Routers
  -m Motes per Gateway
  -C Client Routers
  -G Gateway Routers
  -d Data size (bytes) # Datagram Payload Size
  -r Requests # Number of requests of each client
  -t Timeout (s) # Gateway to UDP network. There is no timeout on XIA network
  
  start   - starts the networks and containers
  stop    - stops all containers
  kill    - kills all containers
  prune   - prune networks and volumes
  build   - build images
  print   - prints configuration
  single  - start in a single network (no routers)

EOF
	exit 0
}

setup()
{
	CLIENTS=1
	CLIENTROUTERS=1
	GATEWAYS=1
	GATEWAYROUTERS=1
	MOTES=1
	TIMEOUT=1
	DATASIZE=8
	REQUESTS=10
	
	FIA=xia
	
	CLIENTIMAGE=$FIA-client
	GATEWAYIMAGE=$FIA-gateway
	CLIENTROUTERIMAGE=$FIA-router
	GATEWAYROUTERIMAGE=$FIA-router
	SERVERIMAGE=$FIA-server

	local OPTARG=$2

	while getopts "c:g:C:G:m:d:t:r" opt; do
		case $opt in			
			c)
				CLIENTS=$OPTARG
				;;
			g)
				GATEWAYS=$OPTARG
				;;
			C)
				CLIENTROUTERS=$OPTARG
				;;
			G)
				GATEWAYROUTERS=$OPTARG
				;;
			m)
				MOTES=$OPTARG
				;;
			d)
				DATASIZE=$OPTARG
				;;
			t)
				TIMEOUT=$OPTARG
				;;
			r)
				REQUESTS=$OPTARG
				;;			
			h)
				help
				;;
			\?)
				printf "\nInvalid option: -$OPTARG\n" >&2
				help
				;;
		esac
	done
}

print_config()
{
	echo
	echo Config:
	echo
	echo Clients: $CLIENTS
	echo Gateways: $GATEWAYS
	echo Client Routers: $CLIENTROUTERS
	echo Gateway Routers: $GATEWAYROUTERS
	echo Motes: $MOTES
	echo Timeout: $TIMEOUT ms
	echo Requests: $REQUESTS
	echo Datasize: $DATASIZE bytes
	echo
	echo Future Internet Architecture: $FIA
	echo
	echo Server Image: $SERVERIMAGE
	echo Gateway Router Image: $GATEWAYROUTERIMAGE
	echo Client Router Image: $CLIENTROUTERIMAGE
	echo Gateway Image: $GATEWAYIMAGE
	echo Client Image: $CLIENTIMAGE
	echo
}

stop_all()
{
	echo "Stoping containers"
	docker stop $(docker ps -a -q)
	docker rm $(docker ps -a -q)
	echo
}

kill_all()
{
	echo "Stoping containers"
	docker kill $(docker ps -a -q)
	docker rm $(docker ps -a -q)
	echo
}

prune_networks()
{
	docker network prune
}

prune_volumes()
{
	echo "Deleting Volume"
	docker volume rm xiotvolume
	echo
	docker volume prune
}

build_all()
{
	cd $XIOTDIR/docker

	cd $FIA-base
	docker build -t $FIA-base .
	cd ..

	cd $SERVERIMAGE
	docker build -t $SERVERIMAGE .
	cd ..
	
	cd $GATEWAYROUTERIMAGE
	docker build -t $GATEWAYROUTERIMAGE .
	cd ..
	
	cd $CLIENTROUTERIMAGE
	docker build -t $CLIENTROUTERIMAGE .
	cd ..

	cd $GATEWAYIMAGE
	docker build -t $GATEWAYIMAGE .
	cd ..
	
	cd $CLIENTIMAGE
	docker build -t $CLIENTIMAGE .
	cd ..
}

star_topology()
{
	echo Data Volume
	docker volume create xiotvolume
	echo
	
	echo Server Network
	docker network create Server_Network	
	echo		
	for i in $(seq 1 $GATEWAYROUTERS)
	do
		echo Gateway_Router_Network_$i
		docker network create Gateway_Router_Network_$i		
		echo
		for j in $(seq 1 $GATEWAYS)
		do      
	   		z="$(( $GATEWAYS * ( $i - 1 ) + $j ))"
	   		echo Gateway_Network_$z
			docker network create Gateway_Network_$z
			echo
	   	done
	done	
	for i in $(seq 1 $CLIENTROUTERS)
	do
		echo Client_Router_Network_$i
		docker network create Client_Router_Network_$i		
		echo		
		for j in $(seq 1 $CLIENTS)
		do
			z="$(( $CLIENTS * ( $i - 1 ) + $j ))"	
			echo Client_Network_$z		
			docker network create Client_Network_$z	
			echo	
		done
	done
	
	echo Server
	docker run -v xiotvolume:/xiotvolume -d --net=Server_Network --name Server $SERVERIMAGE	
	echo
	for i in $(seq 1 $GATEWAYROUTERS)
	do			
		docker network connect Gateway_Router_Network_$i Server
	done
	for i in $(seq 1 $CLIENTROUTERS)
	do	
		docker network connect Client_Router_Network_$i Server
	done
		
	for i in $(seq 1 $GATEWAYROUTERS)
	do
		echo "Gateway Router $i"   		
		docker run -v xiotvolume:/xiotvolume -d --net=Gateway_Router_Network_$i --name Gateway_Router_$i $GATEWAYROUTERIMAGE	
		echo
		for j in $(seq 1 $GATEWAYS)
		do      
	   		z="$(( $GATEWAYS * ( $i - 1 ) + $j ))"
			docker network connect Gateway_Network_$z Gateway_Router_$i
	   	done		
		for j in $(seq 1 $GATEWAYS)
		do      
	   		z="$(( $GATEWAYS * ( $i - 1 ) + $j ))"		
	   		echo "Gateway $z"					
	   		docker run -v xiotvolume:/xiotvolume -d -e GATEWAYROUTER=$i -e GATEWAY=$z --privileged --net=Gateway_Network_$z --name Gateway_$z $GATEWAYIMAGE
	   		echo
	   	done
	done
	for i in $(seq 1 $CLIENTROUTERS)
	do
		echo "Client Router $i"	
		docker run -v xiotvolume:/xiotvolume -d --net=Client_Router_Network_$i --name Client_Router_$i $CLIENTROUTERIMAGE	
		echo
		for j in $(seq 1 $CLIENTS)
		do
			z="$(( $CLIENTS * ( $i - 1 ) + $j ))"	
			docker network connect Client_Network_$z Client_Router_$i
		done
		for j in $(seq 1 $CLIENTS)
		do
			z="$(( $CLIENTS * ( $i - 1 ) + $j ))"		
			echo "Client $z"
			docker run -it -v xiotvolume:/xiotvolume --net=Client_Network_$z -e MOTES=$MOTES -e GATEWAYS=$GATEWAYS -e GATEWAYROUTERS=$GATEWAYROUTERS -e DATASIZE=$DATASIZE -e REQUESTS=$REQUESTS --name Client_$z $CLIENTIMAGE
			echo
		done
	done
}	

single_network()
{
	echo Starting Server
	docker run -d xia-server	
	echo
	for i in `seq 1 $GATEWAYS`;
	do
		echo Starting Gateway
		docker run -d --privileged $GATEWAYIMAGE
		echo
	done
	for i in `seq 1 $CLIENTS`;
	do
		echo Starting Client 	
		docker run -it $CLIENTIMAGE
		echo
	done
}

manual_network()
{
	docker volume create xiotvolume
	
	docker network create servernet
	
	docker network create gatewayrouternet	
	docker network create gatewaynet
		
	docker network create clientrouternet
	docker network create clientnet	
	
	docker run -d --net=servernet -v xiotvolume:/xiotvolume --name server xia-server
	docker network connect gatewayrouternet server
	docker network connect clientrouternet server	
	
	docker run -d --net=gatewayrouternet -v xiotvolume:/xiotvolume --name gatewayrouter xia-router
	docker network connect gatewaynet gatewayrouter
	
	docker run -itd --net=gatewaynet -v xiotvolume:/xiotvolume --privileged --name gateway xia-gateway	
	
	docker run -d --net=clientrouternet -v xiotvolume:/xiotvolume --name clientrouter xia-router
	docker network connect clientnet clientrouter
	
	docker run -it --net=clientnet -v xiotvolume:/xiotvolume -e MOTES=1 -e GATEWAYS=1 -e GATEWAYROUTERS=1 -e DATASIZE=8 -e REQUESTS=10 --name client xia-client
}

#
# SCRIPT STARTS HERE
#
setup $@
shift $((OPTIND-1))

case $1 in
	manual)		
		manual_network
		;;
	single)
		print_config
		single_network
		;;
	print)
		print_config
		;;
	start)
		print_config
		star_topology
		;;
	build)
		build_all
		;;
	prune)
		prune_networks
		prune_volumes
		;;
	stop)
		stop_all
		prune_networks
		prune_volumes
		;;
	kill)
		kill_all
		prune_networks	
		prune_volumes
		;;
	*)
		printf "\nInvalid command\n" >&2
		help
		;;
esac


