#!/bin/sh

sleep $(($DELAY * 3))

# Configure Routes
ip -6 route del default
if [ 'gateways' = $ROUTE ]
  then
	for i in $(seq 1 $GATEWAYROUTERS)
	do
		ip -6 route add aaaa:$i::/64 via dddd:$i::3	
		ip -6 route add cccc:$i::/64 via bbbb::3
	done
	echo gateway
fi

if [ 'clients' = $ROUTE ]
  then
  	for i in $(seq 1 $GATEWAYROUTERS)
	do
		ip -6 route add aaaa:$i::/64 via bbbb::2
	done	
	echo client
fi

# Keep Alive
tail -f /var/log/dmesg
