#!/usr/bin/python
import sys
import os
import time

# find the path to xia-core
XIADIR=os.getcwd()
while os.path.split(XIADIR)[1] != 'xia-core':
    XIADIR=os.path.split(XIADIR)[0]
sys.path.append(XIADIR + '/api/lib')

from c_xsocket import *

def main():
	if len(sys.argv) != 2:
		usage()
	else:
		echotester()

def usage():
    sys.stdout = sys.stderr
    print 'Usage: echoterminal name'
    sys.exit(2) 

def echotester():
	NAME = sys.argv[1]
	MAXLEN = 120
	try:
		sock = Xsocket(XSOCK_DGRAM)
		dag = XgetDAGbyName(NAME)
		while (1):
			print "Please enter the message (blank line to exit):"
			text = sys.stdin.readline()
			text = text.strip()
			if (len(text) == 0):
				break
			latency = time.time() * 1000
			Xsendto(sock, text, 0, dag)
			(data, sdag) = Xrecvfrom(sock, MAXLEN, 0)
			latency = (time.time() * 1000) - latency
			print "received", len(data), "bytes from", sdag,":", data   			
			print "latency: %d ms" % latency	
		Xclose(sock)
	except:
		print "Xsocket error"
		
main()

