#!/bin/sh

service rsyslog start

sleep $(($DELAY * 3))

cd xia-core/bin
./xianet -t start

sleep $(($DELAY * 6))

cd ../applications/example
./echotester $CLIENT $CLIENTROUTER $MOTES $GATEWAYS $GATEWAYROUTERS $DATASIZE $REQUESTS

