#!/bin/bash
#
# Copyright 2017 MonRá
#

XIOTDIR="$(dirname "$(cd "$(dirname "$0")" && pwd)")"
NAME=`basename $0`

help()
{
	cat << EOF

Start or stop the XIoT network testing services.

usage: $NAME [-cgCGmdtr] [-c <clients_per_router>] [-g <gateways_per_router>] [-m <motes_per_gateway>]
             [-C <client_routers>] [-G <gateway_routers>] [-r <resquests>]
             [-t <timeout>] [-d <data_size>]  [start|stop|restart|kill]
where:
  -c Clients per Clients Routers
  -g Gateways per Gateways Routers
  -m Motes per Gateway
  -C Client Routers
  -G Gateway Routers
  -d Data size (bytes)
  -r Requests
  -t Timeout (ms)
  
  start   - starts the network processes if not already running
  stop    - stops the processes
  restart - stops then starts the processes
  kill    - kill all services including orphaned services

EOF
	exit 0
}

setup()
{
	CLIENTS=1
	CLIENTROUTERS=1
	GATEWAYS=1
	GATEWAYROUTERS=1
	MOTES=2
	TIMEOUT=1000
	DATASIZE=8
	REQUESTS=1
	
	FIA=xia
	
	CLIENTIMAGE=$FIA-client
	GATEWAYIMAGE=$FIA-gateway
	CLIENTROUTERIMAGE=$FIA-router
	GATEWAYROUTERIMAGE=$FIA-router
	SERVERIMAGE=$FIA-server

	local OPTARG=$2

	while getopts "c:g:C:G:m:d:t:r" opt; do
		case $opt in			
			c)
				CLIENTS=$OPTARG
				;;
			g)
				GATEWAYS=$OPTARG
				;;
			C)
				CLIENTROUTERS=$OPTARG
				;;
			G)
				GATEWAYROUTERS=$OPTARG
				;;
			m)
				MOTES=$OPTARG
				;;
			d)
				DATASIZE=$OPTARG
				;;
			t)
				TIMEOUT=$OPTARG
				;;
			r)
				REQUESTS=$OPTARG
				;;			
			h)
				help
				;;
			\?)
				printf "\nInvalid option: -$OPTARG\n" >&2
				help
				;;
		esac
	done
}

print_config()
{
	echo
	echo Config:
	echo
	echo Clients: $CLIENTS
	echo Gateways: $GATEWAYS
	echo Client Routers: $CLIENTROUTERS
	echo Gateway Routers: $GATEWAYROUTERS
	echo Motes: $MOTES
	echo Timeout: $TIMEOUT ms
	echo Requests: $REQUESTS
	echo Datasize: $DATASIZE bytes
	echo
	echo Future Internet Architecture: $FIA
	echo
	echo Server Image: $SERVERIMAGE
	echo Gateway Router Image: $GATEWAYROUTERIMAGE
	echo Client Router Image: $CLIENTROUTERIMAGE
	echo Gateway Image: $GATEWAYIMAGE
	echo Client Image: $CLIENTIMAGE
	echo
}

stop_all()
{
	docker stop $(docker ps -a -q)
	docker rm $(docker ps -a -q)
}

kill_all()
{
	docker kill $(docker ps -a -q)
	docker rm $(docker ps -a -q)
}
prune_networks()
{
	docker network prune
}

build_all()
{
	cd $XIOTDIR/docker

	cd $FIA-base
	docker build -t $FIA-base .
	cd ..

	cd $SERVERIMAGE
	docker build -t $SERVERIMAGE .
	cd ..
	
	cd $GATEWAYROUTERIMAGE
	docker build -t $GATEWAYROUTERIMAGE .
	cd ..
	
	cd $CLIENTROUTERIMAGE
	docker build -t $CLIENTROUTERIMAGE .
	cd ..

	cd $GATEWAYIMAGE
	docker build -t $GATEWAYIMAGE .
	cd ..
	
	cd $CLIENTIMAGE
	docker build -t $CLIENTIMAGE .
	cd ..
}

star_topology()
{
	docker network create Server_Network
	#docker run -d --net=Server_Network --name Server $SERVERIMAGE
	docker run -d --name Server $SERVERIMAGE
	sleep 5
	echo "Server initialized"   
	echo
	for i in $(seq 1 $GATEWAYROUTERS)
	do
		docker network create Gateway_Network_$i
		docker run -d --net=Gateway_Network_$i --name Gateway_Router_$i $GATEWAYROUTERIMAGE   
		echo "Gateway Router $i initialized"   
		for j in $(seq 1 $GATEWAYS)
		do      
	   		z="$(( $GATEWAYS * ( $i - 1 ) + $j ))"
	   		docker run -d --net=Gateway_Network_$i --name Gateway_$i $GATEWAYIMAGE
	   		echo "Gateway $z initialized"
	   	done
		echo
	done
	sleep 5
	for i in $(seq 1 $CLIENTROUTERS)
	do
		docker network create Client_Network_$i
		docker run -d --net=Client_Network_$i --name Client_Router_$i $CLIENTROUTERIMAGE
		echo "Clients Router $i initialized"
		for j in $(seq 1 $CLIENTS)
		do
			z="$(( $CLIENTS * ( $i - 1 ) + $j ))"
			docker run --net=Client_Network_$i --name Client_$z $CLIENTIMAGE     
			echo "Client $z initialized"
		done
		echo
	done
}

timeex()
{
	docker run -d xia-server

	sleep 5

	for i in `seq 1 $GATEWAYS`;
	do
	    docker run -d $GATEWAYIMAGE &
	done

	sleep 5

	for i in `seq 1 $CLIENTS`;
	do
 	   docker run $CLIENTIMAGE &
	done
}

#
# SCRIPT STARTS HERE
#
setup $@
shift $((OPTIND-1))

case $1 in
	time)
		print_config
		timeex
		;;
	start)
		print_config
		star_topology
		;;
	build)
		build_all
		;;
	prune)
		prune_networks
		;;
	stop)
		stop_all
		prune_networks
		;;
	kill)
		kill_all
		prune_networks	
		;;
	*)
		printf "\nInvalid command\n" >&2
		help
		;;
esac


