#!/bin/sh

sudo apt-get -y install autogen autoconf libtool libtool-bin bison byacc flex libpcap-dev libgtk-3-dev

cd ~

if [ ! -d "wireshark" ]; then
	git clone https://github.com/XIA-Project/wireshark
else
	cd wireshark
	git pull
	cd ..	
fi

cd wireshark
git checkout xia
cd ..

cd wireshark
./autogen.sh
./configure --with-dumpcap-group=wireshark --enable-setcap-install --with-libcap
make
sudo make install

