#!/bin/sh

cd contiki 
git submodule update --init 

cd tools
make tunslip6

cd cooja
ant run

cd /contiki/examples/ipv6/rpl-border-router 
make TARGET=sky

cd /contiki/examples/cc2538dk/udp-ipv6-echo-server
make TARGET=sky

cd /xia-core/applications/example
make 

