#!/bin/sh

# get XIA source & build
cd /
git clone -b xia-v2 --single-branch https://github.com/XIA-Project/xia-core.git
chmod -R 777 xia-core
cd xia-core
#git checkout xia-v2

# Delete xsockconf.ini files that are not for GENI XIA-prototype
#find . -name "xsockconf*.ini" -exec rm -rf {} \;

./configure
make

