#! /usr/bin/env python
import sys
import socket

def main():
    if len(sys.argv) != 4:
    	usage()
    else:
        echo()

def usage():
    sys.stdout = sys.stderr
    print 'Usage: echo address port message'
    print 'or:    udpecho -c host [port] <file (client)'
    sys.exit(2)    

def echo():
    UDP_IP = sys.argv[1]  # localhost
    UDP_PORT = eval(sys.argv[2])
    MESSAGE = sys.argv[3]
    print "UDP target IP:", UDP_IP
    print "UDP target port:", UDP_PORT
    print "message:", MESSAGE
    sock = socket.socket(socket.AF_INET6, socket.SOCK_DGRAM) # UDP
    sock.sendto(MESSAGE, (UDP_IP, UDP_PORT))
    while True:
        data, addr = sock.recvfrom(1024) # buffer size is 1024 bytes
        print "received message:", data
	
main()

