#! /usr/bin/env python
import sys
import socket

def main():
    if len(sys.argv) != 4:
    	usage()
    else:
        echo()

def usage():
    sys.stdout = sys.stderr
    print 'Usage: echo address port message'
    sys.exit(2)    

def echo():
    UDP_IP = sys.argv[1]  # localhost
    UDP_PORT = eval(sys.argv[2])
    MESSAGE = sys.argv[3]
    print "UDP target IP:", UDP_IP
    print "UDP target port:", UDP_PORT
    print "message:", MESSAGE
    sock = socket.socket(socket.AF_INET6, socket.SOCK_DGRAM) # UDP
    sock.sendto(MESSAGE, (UDP_IP, UDP_PORT))
    while True:
        data, addr = sock.recvfrom(1024) # buffer size is 1024 bytes
        print "received message:", data
        
def check_ping():
    hostname = "taylor"
    response = os.system("ping -c 1 " + hostname)
    # and then check the response...
    if response == 0:
        pingstatus = "Network Active"
    else:
        pingstatus = "Network Error"
    return pingstatus
	
main()


#address = open('../../etc/address.conf').read()
#ad =  re.findall(r'AD:[0-9A-F]+', address, re.I)
#hid =  re.findall(r'HID:[0-9A-F]+', address, re.I)
#dag = "RE %s %s %s" % (ad[0],hid[0],SID) 
